export interface Exercise {
  id: string
  name: string
  sets: number
  reps: number
  weight: number // 무게 속성 추가
  muscleGroup: string
  difficulty: "초급" | "중급" | "고급"
}

export interface DayProgram {
  day: string
  dayNumber: number
  exercises: Exercise[]
  restDay: boolean
}

export const WEEKLY_PROGRAMS: DayProgram[] = [
  {
    day: "월요일",
    dayNumber: 0,
    restDay: false,
    exercises: [
      {
        id: "mon-1",
        name: "스쿼트",
        sets: 4,
        reps: 12,
        weight: 20, // 기본 무게 20KG 추가
        muscleGroup: "하체",
        difficulty: "중급",
      },
      {
        id: "mon-2",
        name: "런지",
        sets: 4,
        reps: 12,
        weight: 20,
        muscleGroup: "하체",
        difficulty: "초급",
      },
      {
        id: "mon-3",
        name: "레그 익스텐션",
        sets: 4,
        reps: 12,
        weight: 20,
        muscleGroup: "하체",
        difficulty: "초급",
      },
      {
        id: "mon-4",
        name: "레그 컬",
        sets: 4,
        reps: 12,
        weight: 20,
        muscleGroup: "하체",
        difficulty: "초급",
      },
      {
        id: "mon-5",
        name: "카프 레이즈",
        sets: 4,
        reps: 12,
        weight: 20,
        muscleGroup: "종아리",
        difficulty: "초급",
      },
    ],
  },
  {
    day: "화요일",
    dayNumber: 1,
    restDay: false,
    exercises: [
      {
        id: "tue-1",
        name: "푸쉬업",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "가슴",
        difficulty: "초급",
      },
      {
        id: "tue-2",
        name: "덤벨 플라이",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "가슴",
        difficulty: "중급",
      },
      {
        id: "tue-3",
        name: "플랭크",
        sets: 4,
        reps: 30,
        weight: 0,
        muscleGroup: "코어",
        difficulty: "초급",
      },
      {
        id: "tue-4",
        name: "사이드 플랭크",
        sets: 4,
        reps: 30,
        weight: 0,
        muscleGroup: "코어",
        difficulty: "초급",
      },
      {
        id: "tue-5",
        name: "트라이셉스 덱스",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "팔",
        difficulty: "초급",
      },
    ],
  },
  {
    day: "수요일",
    dayNumber: 2,
    restDay: false,
    exercises: [
      {
        id: "wed-1",
        name: "데드리프트",
        sets: 4,
        reps: 10,
        weight: 0,
        muscleGroup: "등",
        difficulty: "고급",
      },
      {
        id: "wed-2",
        name: "바벨 로우",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "등",
        difficulty: "중급",
      },
      {
        id: "wed-3",
        name: "힙 쓰러스트",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "둔근",
        difficulty: "중급",
      },
      {
        id: "wed-4",
        name: "스탠딩 컬",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "등",
        difficulty: "중급",
      },
      {
        id: "wed-5",
        name: "사이드 레터럴 레이즈",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "어깨",
        difficulty: "초급",
      },
    ],
  },
  {
    day: "목요일",
    dayNumber: 3,
    restDay: false,
    exercises: [
      {
        id: "thu-1",
        name: "벤치프레스",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "가슴",
        difficulty: "중급",
      },
      {
        id: "thu-2",
        name: "풀업",
        sets: 4,
        reps: 8,
        weight: 0,
        muscleGroup: "등",
        difficulty: "고급",
      },
      {
        id: "thu-3",
        name: "딥스",
        sets: 4,
        reps: 10,
        weight: 0,
        muscleGroup: "가슴",
        difficulty: "중급",
      },
      {
        id: "thu-4",
        name: "사이드 플랭크",
        sets: 4,
        reps: 30,
        weight: 0,
        muscleGroup: "코어",
        difficulty: "초급",
      },
      {
        id: "thu-5",
        name: "트라이셉스 덱스",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "팔",
        difficulty: "초급",
      },
    ],
  },
  {
    day: "금요일",
    dayNumber: 4,
    restDay: false,
    exercises: [
      {
        id: "fri-1",
        name: "오버헤드 프레스",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "어깨",
        difficulty: "중급",
      },
      {
        id: "fri-2",
        name: "사이드 레터럴 레이즈",
        sets: 4,
        reps: 15,
        weight: 0,
        muscleGroup: "어깨",
        difficulty: "초급",
      },
      {
        id: "fri-3",
        name: "바이셉 컬",
        sets: 4,
        reps: 15,
        weight: 0,
        muscleGroup: "팔",
        difficulty: "초급",
      },
      {
        id: "fri-4",
        name: "데드리프트",
        sets: 4,
        reps: 10,
        weight: 0,
        muscleGroup: "등",
        difficulty: "고급",
      },
      {
        id: "fri-5",
        name: "스탠딩 컬",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "등",
        difficulty: "중급",
      },
    ],
  },
  {
    day: "토요일",
    dayNumber: 5,
    restDay: false,
    exercises: [
      {
        id: "sat-1",
        name: "레그 프레스",
        sets: 4,
        reps: 15,
        weight: 0,
        muscleGroup: "하체",
        difficulty: "중급",
      },
      {
        id: "sat-2",
        name: "레그 컬",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "하체",
        difficulty: "초급",
      },
      {
        id: "sat-3",
        name: "카프 레이즈",
        sets: 4,
        reps: 20,
        weight: 0,
        muscleGroup: "종아리",
        difficulty: "초급",
      },
      {
        id: "sat-4",
        name: "사이드 플랭크",
        sets: 4,
        reps: 30,
        weight: 0,
        muscleGroup: "코어",
        difficulty: "초급",
      },
      {
        id: "sat-5",
        name: "트라이셉스 덱스",
        sets: 4,
        reps: 12,
        weight: 0,
        muscleGroup: "팔",
        difficulty: "초급",
      },
    ],
  },
  {
    day: "일요일",
    dayNumber: 6,
    restDay: true,
    exercises: [],
  },
]
